apiVersion: apps/v1
kind: Deployment
metadata:
  name: favourite-service
  namespace: ecommerce
spec:
  replicas: 1
  selector:
    matchLabels:
      app: favourite-service
  template:
    metadata:
      labels:
        app: favourite-service
    spec:
      containers:
        - name: favourite-service
          image: favourite-service:0.1.0
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8800
          envFrom:
            - configMapRef:
                name: ecommerce-config
          resources:
            requests:
              memory: "384Mi"
              cpu: "250m"
            limits:
              memory: "512Mi"
              cpu: "500m"
          readinessProbe:
            httpGet:
              path: /favourite-service/actuator/health
              port: 8800
            initialDelaySeconds: 120
            periodSeconds: 15
            timeoutSeconds: 3
            failureThreshold: 6
          livenessProbe:
            httpGet:
              path: /favourite-service/actuator/health
              port: 8800
            initialDelaySeconds: 150
            periodSeconds: 30
            timeoutSeconds: 3
            failureThreshold: 3
---
apiVersion: v1
kind: Service
metadata:
  name: favourite-service
  namespace: ecommerce
spec:
  selector:
    app: favourite-service
  ports:
    - port: 8800
      targetPort: 8800
  type: ClusterIP
