name: User Service CI/CD Pipeline

on:
  push:
    branches: [develop]
    paths:
      - "user-service/**"
  pull_request:
    branches: [develop]
    paths:
      - "user-service/**"

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: "17"
          distribution: "temurin"
          cache: maven

      - name: Build user-service
        run: |
          cd user-service
          ./mvnw clean package -DskipTests

      - name: Run unit tests
        run: |
          cd user-service
          ./mvnw test

      - name: Upload build artifact
        if: success() && github.event_name == 'push'
        uses: actions/upload-artifact@v4
        with:
          name: user-service-jar
          path: user-service/target/*.jar

  build-and-publish-docker:
    needs: build-and-test
    runs-on: ubuntu-latest
    if: success() && github.event_name == 'push'

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download build artifact
        uses: actions/download-artifact@v4
        with:
          name: user-service-jar
          path: user-service/target

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ${{ secrets.DOCKERHUB_USERNAME }}/user-service
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}}
            type=sha,format=short

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: ./user-service
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
